### ISSUE TITLE
doesn't follow theme nor split views

### ISSUE THREAD

**Issue by syberknight** [Fraser-Greenlee/side-view#2]
i really dig this plugin but...

1) i use dark themes, so this sticks out like a sore thumb.
2) it's huge! wish it could be as thin as the sublime one.
3) no shadow for diferentiation.
4) it doesn't stay on top, so all the code flows over it when on smaller screen w/no word wrap.
5) it only works on one pane; i consistently use 2 panes.

any quick fixes for these things?

**Comment by Fraser-Greenlee** [comment]
Hey I've actually switched to Atom now so I'm not going to be updating any of my extensions but you can try changing the css rules for most of that but Im not sure.

**Comment by syberknight** [comment]
ah, ok, thanks for letting me know!
i've been hearing some stuff about this "Atom" app - i need to go check it out. 
i got sick of Dreamweaver, so tried SublimeText, didn't care for that too much so tried Brackets. stuck with that after spending a week "customizing" it; but still am not very happy with it.
i hear the new Dreamweaver Beta might be cool(?), but i've heard good things about Atom too.
thanks.
